ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = "12 Gauge"
ENT.Author = "Joni"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Firearms: Source 2 - Ammo"
ENT.AmmoType = "12gauge"
ENT.Amount = 20