ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = ".45ACP Ammo"
ENT.Author = "Joni"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Firearms: Source 2 - Ammo"
ENT.AmmoType = ".45acp"
ENT.Amount = 24