ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = ".357 Magnum Ammo"
ENT.Author = "Joni"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Firearms: Source 2 - Ammo"
ENT.AmmoType = ".357magnum"
ENT.Amount = 24