ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = "40MM HE"
ENT.Author = "Joni"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Firearms: Source 2 - Ammo"
ENT.AmmoType = "40mmhe"
ENT.Amount = 1