ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = "7.62x51MM Ammo"
ENT.Author = "Joni"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Firearms: Source 2 - Ammo"
ENT.AmmoType = "7.62x51mm"
ENT.Amount = 20