ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = "23x75MMR Ammo"
ENT.Author = "Joni"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Firearms: Source 2 - Ammo"
ENT.AmmoType = "23x75mmr"
ENT.Amount = 8