ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = "9x18MM Ammo"
ENT.Author = "Joni"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Firearms: Source 2 - Ammo"
ENT.AmmoType = "9x18mm"
ENT.Amount = 24