ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = "5.7x28MM Ammo"
ENT.Author = "Joni"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Firearms: Source 2 - Ammo"
ENT.AmmoType = "5.7x28mm"
ENT.Amount = 100